steps:
  - label: ":spiral_note_pad: Build"
    command: ./bksh add-release-block-step-from-draft
    branches: main
    agents:
      queue: builder

  - wait

  - label: ":git: Create release"
    command: ./bksh create-release
    branches: main
    agents:
      queue: builder

  - wait

  - label: ":git: Delete draft release"
    command: "./bksh delete-draft-release"
    branches: main
    agents:
      queue: builder

  - label: ":rocket: Release"
    command: .buildkite/deploy.sh
    branches: main
    agents:
      queue: deploy-prod
    plugins: *docker
    env:
      NPM_TAG: latest
