steps:
  - label: ":spiral_note_pad: Build"
    command: ./bksh add-release-block-step-from-draft
    branches: master
    agents:
      queue: builder

  - wait

  - label: ":git: Create release"
    command: ./bksh create-release
    branches: master
    agents:
      queue: builder

  - wait

  - label: ":git: Delete draft release"
    command: "./bksh delete-draft-release"
    branches: master
    agents:
      queue: builder

  - label: ":rocket: Release"
    command: .buildkite/deploy.sh
    branches: master
    agents:
      queue: builder
    plugins: &docker
      docker#v3.5.0:
        image: quay.io/widen/builder-nodejs:16
        propagate-environment: true
        environment:
          - ACQUIA_JFROG_TOKEN
          - FORCE_COLOR=true
    env:
      NPM_TAG: latest
